import Lake
open Lake DSL

package liSemantics where
  leanOptions := #[⟨`autoImplicit, false⟩]

@[default_target]
lean_lib LiSemantics where
  roots := #[`Core, `trusted]

/-- Generated by lic build (build/generated/AutoVC.lean). Built when present. -/
lean_lib AutoVC where
  srcDir := "../../build/generated"
  roots := #[`AutoVC]

lean_lib Discharge where
  roots := #[`Discharge]
  deps := #[`LiSemantics, `AutoVC]

lean_lib ProofDB where
  srcDir := "../../proof-db/lean"
  roots := #[`ProofDB]
  deps := #[`LiSemantics, `Discharge]
